name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Run tests
        run: npm test
