name: Code Climate Analysis
run-name: Analisis del code
on:
  push:
    branches:
      - main
jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Run Code Climate analysis
        uses: codeclimate-action/codeclimate-action@v2
        with:
          token: ${{ secrets.CODECLIMATE_TOKEN }}
